# Generated by Django 3.2.3 on 2023-07-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_product_categary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageurl',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
